<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinVer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FirestoreSharp.Core\FirestoreSharp.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="UI\wwwroot\index.html" />
    <EmbeddedResource Include="UI\wwwroot\app.js" />
    <EmbeddedResource Include="UI\wwwroot\style.css" />
  </ItemGroup>

</Project>
